---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver_config:
      network:
      - ["forwarded_port", {guest: 8080, host: 8080, auto_correct: true}]
      - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
      - ["private_network", {ip: "192.168.33.123"}]

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[latexci::default]
    attributes:
